/// @description Init
depth = 8;
image_xscale = choose(1,-1);
alarm[0] = 90;
jumpScared = false;
ghostLocations = [];
loops = GetPlayerLoops();
enoughEnemies = 14;
enoughEnemies += min(loops,30);
alarm[4] = 90;