event_inherited();
image_speed = 0.4;
maxSpeed = 3;
my_health = maxhealth
raddrop=0;
existTime = 0;
team = 0
canMoveOver = false;
canBeMoved = true;
myConfusion = noone;
depth = 2;
snd_hurt = sndHitPlant
hurt_pitch_variation = 0;
frozen=noone;
shadowSprite = shd24;
shadowYoffset = 0;
shadowXoffset = 0;
myCorpse = -1;
totemBuffed = false;
wasResurrected = false;
isSnooze = false;
super = false;
alarm[0] = 20;
friction = 0.4;
image_xscale = choose(1, -1);