scrCrowns();
depth = -998;
alarm[0] = 30;
currentCrown = [];
array_copy(currentCrown,0,Player.crown,0,array_length(Player.crown));
totalCrowns = array_length(currentCrown);
debug(currentCrown);
scrolHeight = 0;
newSelectedCrown = -1;
selectedCrown = -1;
scale = 1;
selectedCrownSprite = sprCrownSelect;
canActuallySelectNow = false;
hoverSelected = false;
image_speed = 0.4;
currentCrownsSurface = -1;
scroll = 0;
debug("create multicrown");