scrCrowns();
depth = -998;
currentCrown = Player.crown;
totalCrowns = array_length(currentCrown);
newSelectedCrown = -1;
selectedCrown = -1;
scale = 1;
selectedCrownSprite = sprCrownSelect;
canActuallySelectNow = false;
hoverSelected = false;