/// @description Init
text = "";
dullText = "";
audio_stop_all();
alarm[0] = 90;
inputDelay = 5;
alarm[2] = inputDelay;
canSkip = true;
with MusCont
{
	audio_stop_sound(song);
	song = musCredits;
	snd_loop(song);
	audio_sound_gain(song,max(0,UberCont.opt_musvol),0);
	
	amb = amb0c;
	if !audio_is_playing(amb)
		snd_loop(amb)
	audio_sound_gain(amb, max(0, UberCont.opt_ambvol), 0);
}
type = 0;
creditIndex = 0;
credits = [
["A <w>GAME<w> CREATED BY <y>VLAMBEER<y>",260],
["A <g>MOD<g> CREATED BY <y>ERDEPPOL<y>",260],
["<w>PROJECT LEAD, DESIGN & DEVELOPMENT<w>#JAN WILLEM NIJMAN",250],
["<w>PRODUCTION & ADDITIONAL DEVELOPMENT<w>#RAMI ISMAIL",240],
["<w>ART DIRECTION, LEAD ARTIST & ANIMATION<w>#PAUL VEER",230],
["<w>ORIGINAL SOUNDTRACK<w>#JUKIO KALLIO",230],
["<w>SOUND DESIGN<w>#JOONAS TURNER",230],
["<w>ADDITIONAL ARTWORK<w>#JUSTIN CHAN",200],
[
"<w>ADDITIONAL MUSIC CREDITS<w>#"+
"#"+
"<w>OASIS<w>#"+
"JUKIO KALLIO#"+
"DANNY BARANOWSKI#"+
"#"+
"<w>PIZZA SEWERS<w>#"+
"JUKIO KALLIO#"+
"EIRIK SUHRKE#"+
"#"+
"<w>VENUS<w>#"+
"JUKIO KALLIO#"+
"ADAM 'DOSEONE' DRUCKER#"+
"#"+
"<w>CURSED CAVES<w>#"+
"JUKIO KALLIO#"+
"RICHARD 'DISASTERPEACE' VREELAND#"+
"#"+
"<w>JUNGLE<w>#"+
"JUKIO KALLIO#"+
"DANIEL HAGSTROM#"+
"#"+
"<w>MANSION & HYPER CRYSTAL<w>#"+
"JUKIO KALLIO#"+
"JOONAS TURNER#"
,300],
[
"<w>TEA BREAK<w>#"+
"ORIGINAL COMPOSITION BY EIRIK SUHRKE#"+
"#"+
"<w>ADDITIONAL MUSIC CONSULTATION<w>#"+
"JOONAS TURNER",200],
[
"<w>THE VOICE OF FISH, CRYSTAL, EYES#"+
"MELTING, PLANT, STEROIDS,#"+
"ROBOT, CHICKEN, HORROR,#"+
"YUNG CUZ, ENEMIES & BOSSES<w>#"+
"JOONAS TURNER#"+
"#"+
"<w>REBEL & ADDITIONAL IDPD<w>#"+
"ISA AND#"+
"#"+
"<w>Y.V> & VENUS ENEMIES<w>#"+
"ADAM DRUCKER#"+
"#"+
"<w>FROG<w>#"+
"JUKIO KALLIO#"+
"#"+
"<w>CAPTAIN<w>#"+
"MYY LOHI#"+
"#"+
"<w>ROGUE<w>#"+
"DANIELLE MCRAE#"+
"#"+
"<w>ADDITIONAL IDPD<w>#"+
"NIILLO TAKALAINEN#"
,360],
[
"<w>LANGUAGE DESIGN<w>#"+
"JOONAS TURNER#"+
"#"+
"<w>BACKEND PROGRAMMING#"+
"COMMUNITY MANAGEMENT#"+
"RELEASE MANAGEMENT<w>#"+
"RAMI ISMAIL"
,230],
/*[//SKIP THIS ONE???
"<w>TRAILERS<w>#"+
"BRAM RUITER#"+
"DANIEL CARNEIRO#"+
"KERT GARTNER#"+
"MARLON WIEBE#"+
"#"+
"<w>EVENT LOGISTICS<w>#"+
"ADRIEL WALLICK#"+
"FRED WOOD#"+
"JON KAY#"+
"MAYA KRAMER#"+
"RAMI ISMAIL",160],*/
[//SKIP THIS ONE???
"<w>MARKETING<w>#"+
"RAMI ISMAIL#"+
"#"+
"<w>ADDITIONAL MARKETING<w>#"+
"JAN WILLEM NIJMAN#"+
"JOONAS TURNER#"+
"JUKIO KALLIO#"+
"JUSTIN CHAN#"+
"PAUL VEER#",230],

//ultra mod
["<g>ULTRA MOD<g>",230],
["<w>PROJECT LEAD, DESIGN, DEVELOPMENT#"+
"SOUND & ART<w>#"+
"<g>ERDEPPOL<g>#"+
"JUUL",300],
["<w>SOUND DESIGN<w>#<g>ONI<g>#<g>LARJE100<g>",200],
["<w>ART<w>#<g>NARCISE YOKU<g>#<g>DAPHNESUKI<g>#<g>VADIMNRSHA<g>",200],
["<w>ADDITIONAL ART<w>#<g>CARLOSBV#GURU JR#NOTYOURSAGITTARIUS#RICOTTAKITTEN#YUVO<g>",200],
[
"<w>ULTRA MUTATION ART<w>#<g>LYNZKAR#LUNARSHARDS#SEYMOUR SCHLONG#SKURLETON#TILDE_BEE<g>##"+
"<w>CONCEPT ART<w>#<g>SOURPUSS<g>##",200],
["<w>NUCLEAR THRONE ULTRA WIKI<w>#<g>ELRACHOXD#SEYMOUR SCHLONG#PERSEPHONE ORION<g>",200],

//TESTERS
["<w>BETA TESTERS<w>#<g>"+
"AGENTCUCCO#"+
"AQUATSUNAMI#"+
"BARGLE#"+
"BASE4 / SPENCERS145#"+
"BOLTMARROW#"+
"CARLOSBV#"+//CANT FIND A BUG REPORT?
"DAPHNESUKI#"+
"DOORKNOB#"+
"ELRACHOXD#"+
"ELTORMAKZXD#"+
"FRILIN"+
"GURU JR#"+
"HAPPYEYE#"+
"KAZ!#"+
"KTHAAR#"+
//"LOTION5238#"+ ???
"MARTIN0304#"+
// "GREG/MLEM5933#"+//GREG only one bug report?
"MR. G & W JAB<g>"
,400],//ALPHABETICAL PLEASE
["<w>BETA TESTERS<w>#<g>"+
"MICROSANDMAN#"+
"MAKORON#"+
"NARCISE YOKU#"+
"OCTO413#"+
"ODDISHTHOUGHTS#"+
"ONI#"+
"PAPERPERMANENT#"+
"PLASMA#"+
"RAYMEY#"+
"SHADY_WILLOWS#"+
"SKELEOP#"+
"SNOPINGAS#"+
"SOURPUSS#"+
"SPEED_OREO#"+
"STICK-E-JO#"+
"PERSEPHONE ORION#"+
"SUMMERSIDETEA#"+
"TABY#"+
"TURTLE MELON#"+
"TUMMY#"+
"THATSLIMEBOI#"+
"THEGREENDIGI#"+
"VADIMNRSHA#"+
"WOODROWMANUEL<g>"
,400],//ALPHABETICAL PLEASE


["<w>VOICES OF HANDS, ATOM#IDPD & SEVERAL OTHER ENEMIES<w>#<g>ONI<g>##"+
"<w>VOICES OF PANDA, VIKING, WEAPONSMITH#HUNTER, DOCTOR, ELEMENTOR#AND SEVERAL ENEMIES<w>#<g>ERDEPPOL<g>",300],

["<w>MUSIC USED<w>##"+
"<w>INVERTED SEWERS<w>#<g>LARJE100<g>##"+
"<w>IDPD TANK<w>#<g>SPLATTIE<g>##"+
"<w>CROSSING THE SWAMP<w>#PLUME, FRED LENOARD & LAURENT PARISI##"+
"<w>CROOKED CROW#REPEAR'S BATTLE<w>#DAVID FENN##"+
"<w>NOSK<w>#CHRISTOPHER LARKIN"
,300],
["<w>MUSIC USED<w>##"+
"<w>CHIMERA<w>#DISASTERPEACE##"+
"<w>THE LAVA STREAM#THE LAVA TOWER<w>#ERIC CHEVALIER##"+
"<w>CONFRONTING MYSELF#REFLECTIONS<w>#LENA RAINE##"+
"<w>NAMACHUUKEI 68-GAME SET (SCC VER)<w>#T4N3##"+
"<w>UNDER WATER (MIX)<w>#TUCKER HUX MARRAY IWANNABETHECOLLECTOR"
,300],
["<w>SPECIAL THANKS<w>#"+
"<g>BASE4 / SPENCERS145#"+
"BLACKINK-303#"+
"BURRINO#"+
"CHUBBYEMU#"+
"IDEAOT/CORNCRAB#"+
"JODI#"+
"KAKUJO#"+
"SLEEPCYCLES#"+
"TURTLE MELON#"+
"VERIBERRIZ#"+
"YELLOWAFTERLIFE<g>"
,360],
[
"<w>NUCLEAR THRONE WAS CREATED USING#"+
"YOYOGAMES GAMEMAKER: STUDIO#"+
"#"+
"NUCLEAR THRONE EXTENDS ITS THANKS TO#"+
"COOL BIG MONY BIZNIZ INC.#"+
"FOR PROVIDING THE IMAGE OF YUNG VENUZ.<w>",230],
["THANK YOU FOR PLAYING!",120],
["SHOWLOGO",0],
["",90],
];
wepA = 0;
wepB = 0;
wepC = 0;
sit = sprMutant1Sit;
wave = 0;