/// @description Start a conversation
var t = "";
if UberCont.char_void_entered[race] == 1
{
	t = scrText(race - 1, 0);
}
else if specialConditionMet > -1
{
	//HERE SPECIAL LORE!
	t = scrText(race - 1, 4, specialConditionMet);
}
else if loops < 2
{
	if random(3) < 1
	{
		t = "I SEE SOME PATHWAYS THAT MAY NOT BE OBVIOUS*";
		t += choose(
		"IF YOU LEAVE A SHEEP ALIVE IN WONDERLAND*YOU MAY ENTER BANDITLAND BY EATING A BIG RED MUSHROOM",
		"TRY THE INVERSION MAGNET ON A HOLE IN THE DESERT",
		"KILL BIG DOG WHILE NEAR FULL HEALTH*THEN TOUCH THE DRAGON SKULL",
		"WITH LAST WISH A FLOWER WILL APPEAR IN FROZEN CITY",
		"NEARLY EVERY SHANKING MELEE WEAPON SHOULD BE ABLE TO FIX A CAR IN THE SCRAPYARDS",
		"A PINK SHEEP RESIDES INSIDE THE CROWNVAULT IN THE FROZEN CITY*DESTROY IT BEFORE IT CHARGES TO FREE THE SHEEP",
		"THE LABS, Y.V. MANSION AND LATERON WONDERLAND*THOSE PLACES ALL HAVE A MUSHROOM THAT WILL BRING YOU TO THE SWAMP*YOU MUST SACRIFICE A WEAPON MOD THERE",
		"THE BRIGHT LIGHT IN THE CRYSTAL CAVES*WILL BRING YOU TO THE CLOUDS*THE MUTATIONS YOU MUST SACRIFICE WILL BE RETURNED IF YOU BEAT ITS CHALLENGE",
		"AFTER A FEW VISITS IN THE CROWNVAULT*A GATEWAY TO ITS COURTYARD WILL APPEAR*HERE YOU WILL FIND THE MULTI CROWN",
		"A WEAPON BOX IN THE PALACE CAN BRING YOU TO SEVERAL DIFFERENT PLACES DEPENDING ON THE WEAPON YOU PUT IN*TRY A CURSED WEAPON*YOU GET YOUR WEAPON BACK UPON DEFEATING THE BOSS",
		"A WEAPON BOX IN THE PALACE CAN BRING YOU TO SEVERAL DIFFERENT PLACES DEPENDING ON THE WEAPON YOU PUT IN*TRY AN ULTRA WEAPON*YOU GET YOUR WEAPON BACK UPON DEFEATING THE BOSS",
		"A WEAPON BOX IN THE PALACE CAN BRING YOU TO SEVERAL DIFFERENT PLACES DEPENDING ON THE WEAPON YOU PUT IN*TRY A GOLDEN WEAPON*YOU GET YOUR WEAPON BACK UPON DEFEATING THE BOSS");
	}
	else
	{
		t = scrText(race - 1, loops + 1);
	}
}
else if loops == 5
{
	t = choose("WHAT WAS THAT?","WHERE DID THOSE GUYS COME FROM?","THE VOID DOES SOME STRANGE THINGS");
}
else
{
	t = scrText(race - 1, 3);
}
textQueue = string_split(t,"*");
/*
var al = array_length(textQueue);
for (var i = 0; i < al; i ++)
{
	if string_letters(textQueue[i]) == ""
		textQueue[i] = 0;
	else
		textQueue[i] = string_letters(textQueue[i]);
}*/
textQueue[array_length(textQueue)] = "";
dialogueStep = 0;
with TextHandler
{
	text = other.textQueue[other.dialogueStep];
}
alarm[2] = 5;