/// @description xxx
owner = -1;
alarm[0] = 60; //Sucktime
alarm[1] = 5;
dmg = 4;
image_speed = 0;
xOffset = 0;
yOffset = 0;
team = 2;
Mod1=0;
Mod2=0;
Mod3=0;
Mod4=0;
confDropChanceIndex = -1;
itemDropChanceIndex = -1;
weaponDropChanceIndex = -1;
wepFire = 0;
hadSpeedApplied = false;
poppop = false;
canBeMoved = true;
team = 2